version: "3"

services:
  furynode0:
    container_name: furynode0
    image: "fury/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-fury.log}
    volumes:
      - ./localnet-setup/node0/fury:/fury:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  furynode1:
    container_name: furynode1
    image: "fury/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-fury.log}
    volumes:
      - ./localnet-setup/node1/fury:/fury:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  furynode2:
    container_name: furynode2
    image: "fury/node"
    environment:
      - ID=2
      - LOG=${LOG:-fury.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/fury:/fury:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  furynode3:
    container_name: furynode3
    image: "fury/node"
    environment:
      - ID=3
      - LOG=${LOG:-fury.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/fury:/fury:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
