version: "3"

services:
  nautidnode0:
    container_name: nautidnode0
    image: "nautid/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-nautid.log}
    volumes:
      - ./localnet-setup/node0/nautid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  nautidnode1:
    container_name: nautidnode1
    image: "nautid/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-nautid.log}
    volumes:
      - ./localnet-setup/node1/nautid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  nautidnode2:
    container_name: nautidnode2
    image: "nautid/node"
    environment:
      - ID=2
      - LOG=${LOG:-nautid.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/nautid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  nautidnode3:
    container_name: nautidnode3
    image: "nautid/node"
    environment:
      - ID=3
      - LOG=${LOG:-nautid.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/nautid:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
